config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "about", to: "about#index"

  get "create_post", to: "posts#new", as: 'creat_post'
  post "create_post", to:"posts#create"

  get 'users/:id', to: 'posts#index', as: 'view_profile'

  #'as': is needed because if plural term like posts is used then url gets .id instead of /id
  get 'view_posts/:id', to: 'posts#view', as: 'view_post'
  get 'view_post/:id', to: 'posts#edit', as: 'edit_post'

  patch "view_post/:id", to: 'posts#update'
  delete 'view_posts/:id', to: 'posts#destroy', as: 'delete_post'

  resources :comments

  resources :likes

  resources :follows

  root to: "main#index"

  #viewing public feed
  get "explore", to: "main#public"

  #viewing followed users feed
  get "following", to: "main#following"

  #viewing a (public) post (REDUNDANT I think)
  #get 'public_posts/:id', to: 'posts#public', as: 'view_public_post'

  get "users/:id/followers", to: 'follows#showFollowers', as: 'view_followers'
  get "users/:id/following", to: 'follows#showFollowing', as: 'view_following'

  post "users/:id", to: "follows#cancel"

  get "search", to: "searchs#index"

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  #except is used since we want non-users to also access the homepage
  before_action :authenticate_user!, :except => [:index]

  def index
  end

  def following
    @followedUsers = current_user.followings
  end

  #we only want signed in users to be able to view posts
  def public
    @posts = Post.all
  end

end

app/views/main/following.html.erb
<div class="jumbotron bd-highlight">
  <div class = "container text-center">

    <br>

    <div class="alert alert-primary">
      <strong>
        <h2>
          Your Feed:
        </h2>
      </strong>
    </div>

    <br>

    <table class="table table-bordered table-striped bg-white">
          <tr>
            <th>User</th>
            <th>Post</th>
            <th>Likes</th>
            <th>Comments</th>
          </tr>

          <% @followedUsers.each do |f| %>
            <% f.posts.each do |post| %>
              <tr>
                <td>
                  <%= link_to post.user.name, view_profile_path(post.user_id) %>
                </td>
                <td><%= link_to post.caption, view_post_path(post) %></td>
                <td><%= post.likes.count %></td>
                <td><%= post.comments.count %></td>
              </tr>
             <% end %>
          <% end %>
    </table>

  </div>
</div>

app/views/main/index.html.erb
<div class="jumbotron-container text-center">
    <% if user_signed_in? %>
      <div class=" alert alert-primary">
        <strong>
          <h1>
            Welcome @<%= current_user.name %>
            <br>
          </h1>
        </strong>
      </div>


      <div class="container">
        <% if current_user.avatar.attached? %>
          <img src = "<%= (url_for(current_user.avatar))%>" height = "200" max-width = "200">
        <% end %>
      </div>

      <br>

      <h2>
        <u>
          How can we help you?
        </u>
      </h2>

      <br>

      <%= button_to "Create Post", create_post_path, method: :get, class: "btn btn-primary" %>

      <br>

      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>

      <br>

    <% else %>
      <div class="container alert alert-primary">
        <strong>
          <h1>Welcome to Fastgram!</h1>
        </strong>
      </div>

      <br>
      <h2>Sign Up or Sign In to continue!</h2>
    <% end %>
</div>

app/views/main/public.html.erb
<div class="jumbotron bd-highlight">
  <div class = "container text-center">

    <br>

    <div class="alert alert-primary">
      <strong>
        <h2>
          All Public Posts:
        </h2>
      </strong>
    </div>

    <br>

    <table class="table table-bordered table-striped bg-white">
          <tr>
            <th>User</th>
            <th>Post</th>
            <th>Likes</th>
            <th>Comments</th>
          </tr>

          <% @posts.each do |post| %>
            <tr>
              <td><%= link_to post.user.name, view_profile_path(post.user_id) %></td>
              <td><%= link_to post.caption, view_post_path(post) %></td>
              <td><%= post.likes.count %></td>
              <td><%= post.comments.count %></td>
            </tr>
          <% end %>
    </table>

  </div>
</div>