config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "about", to: "about#index"

  get "create_post", to: "posts#new", as: 'creat_post'
  post "create_post", to:"posts#create"

  get 'users/:id', to: 'posts#index', as: 'view_profile'

  #'as': is needed because if plural term like posts is used then url gets .id instead of /id
  get 'view_posts/:id', to: 'posts#view', as: 'view_post'
  get 'view_post/:id', to: 'posts#edit', as: 'edit_post'

  patch "view_post/:id", to: 'posts#update'
  delete 'view_posts/:id', to: 'posts#destroy', as: 'delete_post'

  resources :comments

  resources :likes

  resources :follows

  root to: "main#index"

  #viewing public feed
  get "explore", to: "main#public"

  #viewing followed users feed
  get "following", to: "main#following"

  #viewing a (public) post (REDUNDANT I think)
  #get 'public_posts/:id', to: 'posts#public', as: 'view_public_post'

  get "users/:id/followers", to: 'follows#showFollowers', as: 'view_followers'
  get "users/:id/following", to: 'follows#showFollowing', as: 'view_following'

  post "users/:id", to: "follows#cancel"

  get "search", to: "searchs#index"

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many_attached :images, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy

  #caption should not be null
  validates :caption, presence: true

  #max 5 images per post
  validate :validate_images

  #update username on paste whenever user changes their name
  # def update_username(name)
  #   if self.update_attribute(:username, name)
  #     puts "Success!"
  #   else
  #    puts "Failed to update record. Handle the error."
  #   end
  # end

  private
  def validate_images
    return if images.count <= 5

    errors.add(:images, 'You can upload max 5 images')
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  #what this does is that it checks if a user is logged in
  #it comes with Devise gem
  before_action :authenticate_user!

  #same as view but for when a post is accessed by another user
  #def public
  #  @post = Post.find(params[:id])
  #  @comment = @post.comments.build
  #end

  #the create_post page is only returned if a user is actually logged in
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to view_post_path(@post), flash: { alert: "Posted" }
    else
      flash[:alert] = "Incorrect!"
      render :new, status: :unprocessable_entity
    end

  end

  def index
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def view
    @post = Post.find(params[:id])
    #@like = @post.likes.build
    @comment = @post.comments.build
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy

    redirect_to "/view_posts", flash: { alert: "Deleted" }
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      #keep flash before redirect, otherwise it throws error although the post updates and redirection is done
      flash[:alert] = "Edited Post!"
      redirect_to "/view_posts"
    else
      flash[:alert] = "Incorrect!"
      render :new, status: :unprocessable
     end
  end

  private

  def post_params
    params.require(:post).permit(:id, :caption, :images => []).with_defaults(user_id: current_user.id)
  end

end

app/views/posts/edit.html.erb
<div class = "jumbotron">
  <div class="container text-center">
    <br>

    <h1 class="bg-secondary text-white">
      <u>
        Edit Post Details
      </u>
    </h1>

    <br>

    <div class="container">
      <%= form_with model: @post, url: edit_post_path do |form|%>

        <% if @post.errors.any? %>
          <div class="alert alert-danger">
            <% @post.errors.full_messages.each do |message|%>
            <div>
              <%=message%>
            </div>
            <%end%>
          </div>
        <%end%>

        <h4>
          <br>

          <label name='post_caption'>Caption:</label>
          <%= form.text_field :caption, class: "form-control", :required => true%>

          <br>

          <label name='post_images'>Images </label>
          <%= form.file_field :images, :multiple => true , class: "form-control", :required => true%>

        </h4>

        <br>

        <%= form.submit "Edit", class: "btn btn-lg btn-primary" %>

        <br>

      <% end %>
    </div>

  </div>
</div>

app/views/posts/index.html.erb
<div class="jumbotron bd-highlight">

  <div class = "container text-center">

    <br>

    <div class="row">

      <div class="col-6 alert alert-primary">
        <strong>
          <h2>
            @<%= @user.name %>
          </h2>
        </strong>

        <br>

        <div class="container">
          <% if @user.avatar.attached? %>
            <img src = "<%= (url_for(@user.avatar))%>" height = "250" max-width = "250">
          <% end %>
        </div>

        <br>

      <h4>
        <%= @user.bio %>
      </h4>

      </div>

      <div class="col">
          <br>
          <br>

          <div>
            <h5>

              Posts:
              <%= link_to @user.posts.count, view_profile_path(@user.id), class: "text-black", method: :get %>

              &nbsp;
              &nbsp;
              &nbsp;

              Followers:
              <%= link_to @user.received_follows.count, view_followers_path(@user.id), class: "text-black", method: :get %>

              &nbsp;
              &nbsp;
              &nbsp;

              Following:
              <%= link_to @user.followings.count, view_following_path(@user.id), class: "text-black", method: :get %>
            </h5>
          </div>

          <br>
          <br>

          <% if (@user.id != current_user.id) %>

            <% existing_follow = @user.received_follows.find { |follow| follow.follower_id == current_user.id} %>

            <%# if user is followed, then unfollow option is displayed %>
            <% if existing_follow %>
              <%= button_to '', {:controller => "follows", :action => "destroy", :id => @user.id}, class: "btn btn-lg btn-danger fa-2x fa-sharp fa-solid fa-user-slash", method: :delete %>

            <%# if post is not followed, then follow option is displayed %>
            <% else %>
              <%= button_to '', {:controller => "follows", :action => "create", :id => @user.id}, class: "btn btn-lg btn-primary fa-2x fa-sharp fa-solid fa-user", method: :post %>
            <% end %>

          <% end %>

          <br>
          <br>

      </div>

    </div>

    <br>

  <% @posts.each do |post| %>
    <div class="row">

      <div class = "col"></div>

      <div class="col-6 bg-white">

              <br>
              <caption>
                <h3>
                  <%= link_to post.caption, view_post_path(post) %>
                </h3>
              </caption>
              <br>

              <img src = "<%= (url_for(post.images.first()))%>" class="mySlides" style="width:100%">

              <br>
              <br>

              <table class="table table-bordered table-striped bg-white">

                <tr>
                  <th>Likes</th>
                  <th>Comments</th>

                  <% if (current_user.id == @user.id)%>
                    <th>Edit</th>
                    <th>Delete</th>
                  <% end %>
                </tr>

                <tr>
                  <td><%= post.likes.count %></td>
                  <td><%= post.comments.count %></td>

                  <% if (current_user.id == post.user_id)%>
                    <td><%= link_to '', edit_post_path(post), class: "btn btn-lg btn-primary fa-solid fa-pen-to-square" %></td>
                    <!--
                      Not to self, sending a delete request with link_to is very bugged at least in rails 7 for some reason
                      Using turbo_method did not work either
                      Therefore button_to is a better option for delete requests
                    -->
                    <td><%= button_to '', delete_post_path(post), class: "btn btn-lg btn-danger fa-solid fa-trash", :method=>:delete %></td>
                  <% end %>
                </tr>
              </table>
      </div>

      <div class="col">
      </div>

    </div>

    <br>
  <% end %>

  </div>
</div>

app/views/posts/new.html.erb
<div class = "jumbotron">
  <div class="container text-center">
    <br>

    <h1 class="bg-secondary text-white">
      <u>
        Add Post Details
      </u>
    </h1>

    <br>

    <div class="container">
      <%= form_with model: @post, url: create_post_path do |form|%>

        <% if @post.errors.any? %>
          <div class="alert alert-danger">
            <% @post.errors.full_messages.each do |message|%>
            <div>
              <%=message%>
            </div>
            <%end%>
          </div>
        <%end%>

        <h4>
          <br>

          <label name='post_caption'>Caption:</label>
          <%= form.text_field :caption, class: "form-control", :required => true%>

          <br>

          <label name='post_images'>Images </label>
          <%= form.file_field :images, :multiple => true , class: "form-control", :required => true%>

        </h4>

        <br>

        <%= form.submit "Post", class: "btn btn-lg btn-primary"%>

        <br>

      <% end %>
    </div>

  </div>
</div>

app/views/posts/view.html.erb
<header>
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <style>
    .mySlides {display:none;}
  </style>
</header>

<div class="jumbotron bd-highlight">

  <div class = "container text-center">

    <div class="w3-content w3-display-container">
      <% @post.images.each do |image| %>
        <tr>
        <td><img src = "<%= (url_for(image))%>" class="mySlides" style="width:100%"></td>
        </tr>
      <% end %>

      <%# only display the gallery navigators if multiple images in a post %>
      <% if @post.images.length > 1 %>
        <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
        <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
      <% end %>

    </div>
  </div>

  <br>

  <div class="container">

    <div class="row">

      <div class = "col text-center">

      <br>

      <% existing_like = @post.likes.find { |like| like.user_id == current_user.id} %>

        <%# if post is liked, then unlike option is displayed %>
        <% if existing_like %>
            <%= button_to '',{:controller => "likes", :action => "destroy", :post_id => @post.id, id: existing_like.id}, class: "btn btn-lg btn-danger fa-2x fa-solid fa-thumbs-down", method: :delete %>

        <%# if post is not liked, then like option is displayed %>
        <% else %>
          <%= button_to '', {:controller => "likes", :action => "create", :post_id => @post.id}, class: "btn btn-lg btn-primary fa-2x fa-solid fa-thumbs-up", method: :post %>
        <% end %>

      </div>

      <div class = "col text-center">
        <div class="alert alert-primary">
          <strong>
            <h2><b>
              <%= @post.caption %>
            </b></h2>
          </strong>
        </div>
      </div>

      <div class = "col">
      </div>

    </div>

  </div>

  <br>

  <div class="container bg-secondary">

    <div class="row">

      <div class = "col"></div>

      <div class = "col bg-white">
        <h2 class="bg-secondary text-white text-center">
          Comments
        </h2>

        <br>

        <%- @post.comments.each do |comment|%>
          <% if (comment.text.present?) %>

            <b> <%= comment.user.name %> </b>

            <br>

            <div class="row">

              <div class = "col">
                <%= comment.text%>
              </div>

              <div class = "col">
                <%# Users can delete their own comments, and Users can delete any comment under their own posts %>
                <% if ((comment.user_id == current_user.id) || (@post.user_id == current_user.id)) %>
                  <%#
                    Since a potential comment (text and username are empty on it) is built by default,
                    so we only display delete button for those comment that have text
                  %>

                  <%= button_to '', {:controller => "comments", :action => "destroy", :post_id => @post.id, :comment_id => comment.id }, class: "fa-solid fa-trash", :method=>:delete, form: {data: {turbo_confirm: 'Are you sure?'}} %>

                <% else %>
                  <br>
                <% end %>

              </div>

            </div>

            <br>
          <% end %>
        <%end%>

        <%= render "comments/form", comment: @comment%>
      </div>

      <div class = "col"></div>

    </div>

  </div>

  <br>

</div>

<script>
  var slideIndex = 1;
  showDivs(slideIndex);

  function plusDivs(n) {
    showDivs(slideIndex += n);
  }

  function showDivs(n) {
    var i;
    var x = document.getElementsByClassName("mySlides");
    if (n > x.length) {slideIndex = 1}
    if (n < 1) {slideIndex = x.length}
    for (i = 0; i < x.length; i++) {
      x[i].style.display = "none";
    }
    x[slideIndex-1].style.display = "block";
  }
</script>